### ISSUE TITLE
Allow formatting of build.txt to be a .json file

### ISSUE THREAD

**Issue by lostthetrail** [jrburke/r.js#837] opened 2015-07-23 23:18 UTC
As I am going through the process of building a SPA, I found the need to chunk out the application. I have done this through using the build optimizers to create small artifacts which contains flows. Each of these flows also needs to be documented as a bundle, so that a end-user only gets the code they are requesting. I can do this all via hardcoding, but it would be smart to generate my require configuration for bundles based on the output of the build optimizer.

And thus the request to format the build.txt as a json file.

Currently the output is something like below:

```text
vendor.js
----------------
jquery.js
underscore.js
backbone.js

app.js
----------------
...

hello.js
----------------
...

reddit.js
----------------
...
```

While if it were in a JSON format, I could import it into runtime code and use it to generate my runtime require config.

```javascript
{
  "bundles": {
    "vendor": [
      "jquery",
      "underscore",
      "backbone"
    ],
    "app": [
      ...
    ],
    "hello": [
      ...
    ],
    "reddit": [
      ...
    ],
  }
```

@jrburke Do you see any obvious problems with providing such a feature? I would be happy to make an attempt at adding it if you do not.

**Comment by jrburke** [comment] 2015-07-27 20:52
My first thought is that this would be a good scenario for [amodro-trace](https://github.com/amodrojs/amodro-trace), since it gives the results back in a data format, and gives you much finer grained control over the final bundle contents.

So I am going to close this issue as suggesting going that route, but feel free to continue discussion here.

**Closed by jrburke** 2015-07-27 20:52 UTC

**Comment by lostthetrail** [comment] 2015-07-28 21:47
Do you see people using RequireJS and trying to get a similar chunked experience? For large application the bundle feature is awesome, but very cumbersome due to the manual configuration required. Creating the data-formatted bundle output would provide a mainstream way of helping people solve this.

Or am I going about this all wrong? :)

**Comment by jrburke** [comment] 2015-07-28 23:47
If the issue is mainly just getting the "bundles" config section populated with the right info, issue #613 tracks that issue. I agree r.js should generate it, but some of it was working out the API to do it, and to see if there was a need for it. So if that is the end goal of filing this ticket, let's focus the effort on getting #613 fixed. Leave a comment in that ticket if you want that feature, and I'll make an attempt of describing how it might work/what the config API would be and we can go from there.

**Comment by lostthetrail** [comment] 2015-07-28 23:50
Oh, that is EXACTLY what I was looking for.
