### ISSUE TITLE
Bad order in minified file when using babel/ES6 require.js plugin

### ISSUE THREAD

**Issue by Rush** [jrburke/r.js#808] opened 2015-05-02 15:43 UTC
I am trying to use ES6 plugin for require.js via https://github.com/mikach/requirejs-babel but when using it, something breaks with the order of included plugins and require.js is no longer included as a first module as outlined below:
```js
{
  dir: "out",
  baseUrl: "src",
  paths: {
    "requireLib": "require"
  },
  modules: [
    {
      name: "application",
      include: ["requireLib"]
    }
  ]
}
```

Please download my example to see what I am talking about:
```
wget http://x.rushbase.net/bd9739394d421a56193b26269885d96e4a18ce6b/rjs-bug.zip
unzip rjs-bug.zip
cd rjs-bug
node r.js -o build.js # to see bad output
# Edit src/dep1.js and comment the require line to get good order output
node r.js -o build.js # to see good output
```

When not using the plugin the order is always good, as in `require.js` is always included first:
```
application.js
----------------
require.js
dep1.js
dep2.js
application.js
```

When using the plugin from `src/dep1.js` the order is ALWAYS bad:
```
application.js
----------------
babel.js
es6.js
es6!es6dep
dep1.js
dep2.js
application.js
require.js
```

Funnily enough, if we added some other module (not using the ES6 plugin), the order would be broken as well! Require.js would land at the end.

I expect to always see `require.js` as first, as otherwise it doesn't work.

**Comment by tbranyen** [comment] 2015-05-02 16:52
I believe this is a bug with the optimizer's `modules` configuration.  I was able to get the expected behavior, by changing your build.js to the following:

``` javascript
{
  dir: "out",
  baseUrl: "src",
  paths: {
    "requireLib": "require"
  },
  name: "requireLib",
  include: ["application"],
  insertRequire: ["application"]
}
```

If you need a temporary solution, this should work fine for your use case for now.

**Comment by jrburke** [comment] 2015-05-02 17:12
I did a pass through the debugger, and the main issue is that babel.js includes a `define.amd={}`. If r.js sees that, then it thinks the file is defining the AMD module API and hoists it to the top. r.js will take the first file it thinks defines the AMD API and hoist it. Since babel is parsed before requireLib, it wins the spot.

So @tbranyen's solution works around the issue by making sure requireLib is first, so that is a good way to go if you need a quick fix. Another solution might be to use onBuildRead and onBuildWrite hooks, in the onBuildRead hook, return an empty string for 'babel', but for the onBuildWrite, make sure it is the full babel contents. @tbranyen's is a simpler more declarative solution though, but it means likely renaming the output requireLib.js to your application.js after r.js runs, or allowing the HTML to load that built requireLib.js file instead of application.js.

I don't know enough about babel and its internals to know why it might need to do the define definition. It also might be a nested, locally defined define and not the global define, so in an ideal world would not qualify as declaring an AMD API? I wouldn't mind someone else tracing that down though as I do not use babel.

I could look at restricting the hoist detection code to try to only target define.amd calls for defines that are globally declared perhaps? Although that can also be tricky to test for possible variants, like `window.define`, `window['define']`, that sort of stuff. It would likely be a limited form of detection.

I'll place this in the 2.1.18 bucket for more consideration, but probably needs more analysis of why babel is qualifying for hoisting here, and need to weigh the risks of possibly missing some AMD definitions by a stricter check.

**Comment by Rush** [comment] 2015-05-02 18:00
Thanks for taking a look at this. Unfortunately this workaround will not work in my case as I am building multiple modules. :-( I will probably wait with my use of ES6 until we can come up with some other solution.

**Comment by Rush** [comment] 2015-05-02 18:02
Babel is converting the ES6 import do define, maybe this is tripping require.js checks?

**Comment by jrburke** [comment] 2015-05-02 21:41
The conversion to define() calls is fine and expected, the tricky part is that babel.js in its source code does `define.amd = {}`, which is something only an AMD loader or AMD API provider, like requirejs or almond would do. 

Perhaps the assumption is that babel.js would be used for loading the define()'d modules instead of another loader? I didn't think that was the case, I thought it allowed for other AMD loaders/API providers but I am not very familiar with babel.

**Comment by Rush** [comment] 2015-05-02 22:58
It seems a little bit more clear here (not uglified source) https://raw.githubusercontent.com/hipertracker/requirejs-babel/master/babel.js - this is `amdefine` that's tripping this then? Is this node stuff just accidentally left there in a browser build of theirs?

**Comment by jrburke** [comment] 2015-05-03 01:24
Ah, yes, it looks like a browserify build of some stuff installed via npm, and one of the dependencies uses amdefine, something I wrote (ha!), to get a local define for some of the internal modules. So I think I can work up a way to avoid treating that as the global define since it is defined inside a function. I will look at a fix for this for 2.1.18.

**Comment by Rush** [comment] 2015-05-03 09:16
Thanks!

**Closed** 2015-05-06 00:31 UTC

**Comment by jrburke** [comment] 2015-05-06 00:32
I have a provisional fix in the latest master snapshot. If you have the time, I would appreciate a sanity check that this is the only change that is needed to get the example to work correctly:

https://raw.githubusercontent.com/jrburke/r.js/master/dist/r.js

**Comment by Rush** [comment] 2015-05-06 20:35
Order looks good but I see something different that is odd. It seems that exclude does not work.
http://x.rushbase.net/deea88f0450f6b71b9ed739ad0754f1fa658e9fe/rjs-bug.zip

`build.js`
```js
{
  /* ... */
  pragmasOnSave: {
    excludeBabel: true
  }
}
```
parts in `es6.js`:
```js
define([
    //>>excludeStart('excludeBabel', pragmas.excludeBabel)
    'babel',
    //>>excludeEnd('excludeBabel')
    'module'
], function(
    //>>excludeStart('excludeBabel', pragmas.excludeBabel)
    babel,
    //>>excludeEnd('excludeBabel')
    _module
    ) {
```

Final `application.js` size: > 700KB where it should be single digit KB size.

**Comment by jrburke** [comment] 2015-05-13 18:14
That happens because pragmasOnSave only take effect when saving the file in the output, which is after dependency tracing to what include in the build has already occurred.

For this particular case, it is enough to also add a `exclude: ['babel']` next to the `include` config to avoid babel from showing up in the built application.js.

It will be hard to do it otherwise with pragmas. If you use `pragmas` instead of `pragmasOnSave`, that would break the building part since the es6 loader plugin wants to participate in the build.
