### ISSUE TITLE
shim with defined module causes ENOENT

### ISSUE THREAD

**Issue by lwr** [jrburke/r.js#831] opened 2015-07-10 10:57 UTC
Test Case

-  `/options.js`
``` js
{
    appDir: './www',
    baseUrl: './',
    mainConfigFile: 'www/1.js',
    dir: './www-built',
    optimize : 'none',
    modules: [
        {
            name: '1',
            include: []
        },

    ]
}
```

- `/www/1.js`
``` js
require.config({
    shim : {
        '1' : ['1-0']
    }
});

define('1-0', []);

require(['1-0'], function(){
    console.log('1 inited');
});

```

Test Result
```bash
> node r.js -o options.js

Tracing dependencies for: 1
Error: Error: ENOENT, no such file or directory '/Users/lwr/tmp/www-built/1-0.js'
    at Error (native)
```

Expecting result (after remove shim)
```bash
Tracing dependencies for: 1

1.js
----------------
1.js
```

**Comment by jrburke** [comment] 2015-07-11 02:09
This should work better `define('1-0', {});`. Using an ID then a dependency array with no dependencies and no factory function looks like it is not an AMD define() call. The optimizer tries to only match define() calls that look like AMD calls, to avoid false positives with a define API that might be specific to the application. The choices for what looks like a valid define() are a bit subjective, but I want to be careful about not stepping on other define APIs.

Closing with the suggestion of the alternative type of define. Feel free to add more details though and we can reopen as needed.

**Closed by jrburke** 2015-07-11 02:09 UTC

**Comment by lwr** [comment] 2015-07-11 14:34
@jrburke changes `define('1-0', [])` to `define('1-0', {})` or `define('1-0', [], {})` does not do any help.

I'm sorry I do not describe the use case very clear.
Actually the config is liked this

```js
require.config({
    shim : {
        'entry' : ['init']
    }
});

define('init', ['init-module-1', 'init-module-2', ...]);

require(['entry']);

```

We have some init dependencies for our project which must be loaded before all others.
We do not want to repeat the module list times and times, su we defined init module as an alias.

I knew I can remove `init` in this case (the init module list can be declared directly in shim list).
Some times is not so easy to do this.

I even can declare the init module in separated file.

But I think it should be clearly a bug of `r.js` that enforcing all of us to declare all modules in separated files, do you agree?

**Comment by jrburke** [comment] 2015-07-11 17:36
Ah, if there are dependencies, then using an empty function for the third arg should match the define detection: `define('init', ['init-module-1', 'init-module-2', ...], function() {});`

**Comment by lwr** [comment] 2015-07-11 17:39
@jrburke I have try empty string / empty object / empty function / not empty function but all failed with the same error :(

**Comment by jrburke** [comment] 2015-07-12 06:24
Ah, so tried this locally and the issue is the shim config. With options.js specifying mainConfigFile for 1.js, it parses out the shim config there first, then proceeds to trace for "1" for the optimization. However, before "1" is even loaded, since the shim config is already active in the optimizer, the optimizer attempts to load "1-0".

So it is not a matter of the inline define() in "1" not getting parsed, but the shim config stating that "1-0" should be loaded before loading the "1" file. If I comment out the mainConfigFile line in options.js, then it works.

So my thought is that the optimizer is working correctly given the above config. shim config that specifies dependencies means those dependencies are attempted to be loaded first. I think the build situation needs to decide if this is truly a shim config situation, and if so, remove the inline define for a shimmed dependency in the script being shimmed. Or, remove the shim config from the build setup, by commenting out the mainConfigFile.

**Comment by lwr** [comment] 2015-07-14 10:01
I have workaround this issue by using this config pattern
```js
require.config({
    shim : {
        'app'           : ['bootstrap-init', 'init-module-1'],
        'init-module-1' : ['init-module-2', 'init-module-3', ..., 'init-module-n']
    }
});

// it is important for load order: 
// - 'bootstrap' must init first
// - then all other init modules
// - finally run the app (and it's dependencies)
require(['bootstrap-init'], function () {
    require(['init-module-1], function () {
        require(['app']);
    });
});

```

all modules are real
not any predefined alias module (likely 'init'), the 'init-module-1' act as the role
the second shim statement make sure all other init modules are loaded and packaged correctly
