### ISSUE TITLE
Insert only the url of the sourceMap into the minified file

### ISSUE THREAD

**Issue by crebuh** [jrburke/r.js#807] opened 2015-04-29 13:33 UTC
Hi there!

We are using r.js to minify and concatenate the files in our projcet. In addition we are using https://errorception.com/ to track all errors which occur in the production mode.

When we minify our files, at the end of the minified web.min.js two sourceMapppingURL entries were added.

//# sourceMappingURL=web.min.js
//# sourceMappingURL=web.min.js.map

The problem with this is, that errorception assumes that the first sourceMappingUrl is the sourceMap which should be used to resolve the minified file.

Is there a possibility to cut off the first entry during the build process?

**Comment by crebuh** [comment] 2015-05-01 12:14
It is weird, i tested the build process on another machine. There node with v0.10.22 (instead of v0.10.32 where it doesnt work) is running.

Does anybody has an idea, why with 0.10.32 two url's where added during the build-process.

It is not a great deal, i can manually remove that line, before uploading it to the server. But i want to automate the deploy process as far as possible.

**Comment by jrburke** [comment] 2015-05-02 16:38
It does sound odd that such a minor node version would make a difference. 

Maybe if you are doing the build via package.json/node_modules-installed dependencies, doing a fresh fetch of the dependencies from package.json could lead to slightly different point releases being used. If under v0.10.32 the processes is done with a fresh npm install, removing the npm cache and the local node_modules directory, maybe it will give a different result?

Other than that hard to know what to suggest to explain the differences without a test project to try.

**Comment by crebuh** [comment] 2015-05-04 08:35
Yes it is really weird. I deleted the local node_modules directory and cleared the cache, but the problem still exists. 

which files do you need in the sample project?

**Comment by jrburke** [comment] 2015-05-06 00:46
Ideally just the one that has the problem and the build config used to generate it. Hopefully if the file is just "test.js" a single file output build can be done with some sort of config like:

```javascript
{
  baseUrl: ".",
  name: "temp",
  out: "built.js"
}
```
and then to test I can just do a `node r.js -o build.js` in a directory with temp.js and the build config to generate the build.

But whatever is a minimum set to demonstrate the problem.

**Comment by jrburke** [comment] 2015-05-06 01:30
Just reviewing some other bugs, it seems like #802 might be reporting something similar. If that is the same behavior you are seeing then we can close this one as a duplicate of that bug.

**Comment by miguel250** [comment] 2015-06-30 17:32
@jrburke I am also seeing this issue. This is because rjs is setting the `uconfig.outSourceMap` to the base file name [here](https://github.com/jrburke/r.js/blob/ab4d9000e5a6fc76b3b055b0d9c069b53634122b/build/jslib/optimize.js#L458) and the uglifyjs2 is also appending `sourceMappingURL` [here](https://github.com/jrburke/r.js/blob/ab4d9000e5a6fc76b3b055b0d9c069b53634122b/build/jslib/uglifyjs2.js#L7929). After that rjs append `sourceMappingURL` again [here](https://github.com/jrburke/r.js/blob/ab4d9000e5a6fc76b3b055b0d9c069b53634122b/build/jslib/optimize.js#L491)

**Comment by jrburke** [comment] 2015-07-12 07:17
Thanks @miguel250, I tracked a fix in #802 so closing this as a duplicate of that bug.

**Closed by jrburke** 2015-07-12 07:17 UTC
