### ISSUE TITLE
remove .html files after optimization

### ISSUE THREAD

**Issue by lzl124631x** [jrburke/r.js#887] opened 2016-01-29 12:39 UTC
I use 'text' plugin to read html strings from `.html` files. After optimization, the `.html` files are already injected into the built js file and become useless. I want to remove them after optimization. 

Setting `removeCombined` config can help you remove the js files that has been combined, but doesn't work for `.html` files.

Is there a easy way to delete the `.html` files? Or should I use `onModuleBundleComplete` to manually delete those HTMLs?

**Comment by jrburke** [comment] 2016-01-29 22:38
Allowing removeCombined support for loader plugin resources is #344. I am not sure when it will be addressed though, could be a few months. Closing this bug as a duplicate of that other, it has more context too.

**Closed by jrburke** 2016-01-29 22:38 UTC
